---
version: "1"
rules:
  - base: master
    upstream: slacka:master
    mergeMethod: rebase
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
...
