---
# Travis CI Configuration
# https://docs.travis-ci.com

## Lesser history
git:
  depth: 30
dist: focal
addons:
  apt:
    packages:
      - git
      - coreutils
      - autotools-dev
      - gettext
      - libwxgtk3.0-gtk3-dev
      - devscripts
      - equivs
language: cpp
compiler:
  - gcc
script:
  - "./setup-development-environment.bash"
  - mk-build-deps && mv woeusb-build-deps*.deb ..
  - autoreconf -vfi
  - "./configure --prefix=/usr"
  - make -j $(nproc)
before_deploy:
  - git config --local user.name "Peter J. Mello"
  - git config --local user.email "admin@petermello.net"
  - export TRAVIS_TAG=${TRAVIS_TAG:-"$(dpkg-parsechangelog -SVersion)+git$(git log --format=%h -1)"}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: NN8wKxAuC5Q1JU6mj3Avz5r+hsEbcTEdhzIidNfro269jsfOK3JGkSzUj9y4NON1/Y4TpPm7BMJEoyTCpaiH2n52uwc428ezW+6M324pOMavgKXBnGaF38W6WGHe7mWom75kKO1g6zfYNj4y7iZwaqmENecEI+wdbrKTz5T9p7mFOzVw67Sn1jz8E7UksuoTYqpay9EQjdoYYDZ/k4jSRxTYtjDereIsNTKOh3berCdMi6GjIIX2SrqJPmYPnJgXTwJjLqQiCNW1oEXVNm+PTodrwr1QzF624sVGlTLTrcvIlnUU1HnJP0P1VpoPjWwws9+z1QePnIzFMWtp+prvuhCsBjc1D92sBDYa9rpX6Bj2Na54lrmTPN4cBLC0zadAMWdild1HsWMriWCVrcI3WIEzpfRItFRiyqyE1l91+gUIA96THEMDwtGS9oFBQgKH83tnfkOzB4tBMCU7pj3zkIbheDgf7LGGTaqcR/QcHKwM0ycsoUORf4DOI/updHqL8z3nDy6cZmk7KWiyzKPh16ikR+wvy+GIqFyzQXRhuhbSMxchx+lwLStkKECxPhs1Y4MZiovP6Y+sNcm0d/Q1j72yFTJVJxFk/7xz/rTpqu/eLKtfhNZ/h4mGy1boizh5Ytptwy4R3rfCv/PEdw5abPSw3w5g4fpvwe1VwPgVkBA=
  file_glob: true
  file:
    - "../woeusb-*.deb"
    - "../woeusb-*.buildinfo"
    - "../woeusb-*.changes"
    - "../woeusb-*.dsc"
    - "../woeusb-*.orig.tar.xz"
  skip_cleanup: true
  draft: true
  prerelease: true
  # yamllint disable-line rule:truthy
  on:
    repo: RogueScholar/WoeUSB
    branch: debian
    tags: true
...
